[project]
name = "Basic App"
version = "1.0.0"
description = "A Basic Python app using FastAPI to test the API creation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.black]
target-version = ["py311"]

[tool.uv.workspace]
members = [
    "doc_app",
]
